rename `channel` to `renderChannel`, so no const conflict
fixes:

```
SyntaxError: /.../patchcore/message/html/meta/channel.js: "channel" is read-only
   5 | 
   6 | exports.create = (api) => {
>  7 |   return nest('message.html.meta', function channel (msg) {
     |                                    ^
   8 |     const { channel } = msg.value.content
   9 |     if (channel) return h('a.channel', {href: `#${channel}`}, [`#${channel}`])
  10 |   })
```